version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: Admin$273
       MYSQL_DATABASE: ontopoflinux
       MYSQL_USER: umesh
       MYSQL_PASSWORD: Admin$273

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: ontopoflinux
       WORDPRESS_DB_PASSWORD: Admin$273
       WORDPRESS_DB_NAME: ontopoflinux
volumes:
    db_data: {}
